name: Build and deploy
on:
    push:
        tags:
            - v*
jobs:
    build:
        name: Build application
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                node-version: '10.x'
            - run: yarn install
            - run: yarn build      
            - uses: actions/upload-artifact@v1
              with:
                name: application
                path: build/