name: Build and deploy
on:
    push:
        tags:
            - v*
jobs:
    build:
        name: Build application
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                node-version: '10.x'
            - run: yarn install
            - run: yarn build      
            - uses: actions/upload-artifact@v1
              with:
                name: application
                path: build/
    deploy:
        name: deploy to s3
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/download-artifact@v1
              with:
                name: application
            - uses: actions/setup-python@v1
              with:
                python-version: '3.x'
            - run: pip install awscli
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: eu-west-3
            - run: aws s3 sync application s3://${{ secrets.AWS_S3_BUCKET }}